apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: sentinelops-alerts
  namespace: monitoring

spec:
  groups:
  - name: sentinelops.rules
    rules:

    - alert: BackendDown
      expr: up{job="sentinelops-backend"} == 0
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: Backend is down

    - alert: HighCPUUsage
      expr: rate(container_cpu_usage_seconds_total[5m]) > 0.8
      for: 2m
      labels:
        severity: warning
      annotations:
        summary: High CPU Usage

    - alert: PodRestarting
      expr: increase(kube_pod_container_status_restarts_total[5m]) > 2
      for: 1m
      labels:
        severity: warning
      annotations:
        summary: Pod restarting frequently
